spring.application.name=security
# <.>
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
# <.>
spring.sql.init.mode=always

